#!/usr/bin/env python3
"""Emit _style.iuml with every font proportional to one base size.

Why the base size is large: PlantUML's node separation and padding are in fixed
points and do not scale with the font, so a small base font spends most of the
canvas on whitespace and the whole diagram then has to be shrunk hard to fit a
text column. Raising the base font while keeping separation tight raises the
text-to-whitespace ratio, which is what actually determines legibility on the
printed page. All fonts must move together or the smallest one becomes the floor.
"""
import sys
S = int(sys.argv[1]) if len(sys.argv) > 1 else 40
r = lambda k: max(1, round(S * k))
print(f"""' GENERATED by mkstyle.py {S} -- edit mkstyle.py, not this file.
skinparam shadowing false
skinparam defaultFontName Helvetica
skinparam defaultFontSize {S}
skinparam roundCorner {r(0.10)}
skinparam padding 2
skinparam nodesep {r(0.30)}
skinparam ranksep {r(0.42)}
skinparam ArrowColor #37474F
skinparam ArrowThickness {max(1, round(S*0.05))}
skinparam ArrowFontSize {S}
skinparam ArrowFontColor #37474F
skinparam TitleFontSize {r(1.05)}
skinparam TitleFontColor #263238

skinparam componentStyle uml2
skinparam component {{
  BackgroundColor #ECEFF9
  BorderColor #5C6BC0
  FontColor #1A237E
  FontSize {S}
  BorderThickness {max(1, round(S*0.045))}
}}
skinparam interface {{
  BackgroundColor #FFFFFF
  BorderColor #5C6BC0
  FontColor #1A237E
  FontSize {r(0.95)}
}}
skinparam package {{
  BackgroundColor #FAFAFA
  BorderColor #90A4AE
  FontColor #37474F
  FontStyle italic
  FontSize {r(0.92)}
  BorderThickness {max(1, round(S*0.035))}
}}
skinparam node {{
  BackgroundColor #F1F8F4
  BorderColor #66897A
  FontColor #1B5E20
  FontSize {S}
  BorderThickness {max(1, round(S*0.045))}
}}
skinparam database {{
  BackgroundColor #FFF8E1
  BorderColor #A1887F
  FontColor #4E342E
  FontSize {S}
}}
skinparam cloud {{
  BackgroundColor #F5F5F5
  BorderColor #9E9E9E
  FontColor #424242
  FontSize {S}
}}
skinparam artifact {{
  BackgroundColor #FFFDF5
  BorderColor #A1887F
  FontColor #4E342E
  FontSize {r(0.95)}
}}
skinparam note {{
  BackgroundColor #FFFDE7
  BorderColor #BDBDBD
  FontColor #424242
  FontSize {r(0.95)}
}}
skinparam legend {{
  BackgroundColor #FFFFFF
  BorderColor #CFD8DC
  FontSize {r(0.92)}
  FontColor #37474F
}}
skinparam sequence {{
  ArrowColor #37474F
  ArrowFontSize {S}
  LifeLineBorderColor #90A4AE
  LifeLineBackgroundColor #FAFAFA
  ParticipantBackgroundColor #ECEFF9
  ParticipantBorderColor #5C6BC0
  ParticipantFontColor #1A237E
  ParticipantFontSize {S}
  ParticipantPadding {r(0.30)}
  BoxBackgroundColor #FFFFFF
  BoxBorderColor #CFD8DC
  BoxFontSize {S}
  GroupBackgroundColor #FAFAFA
  GroupBorderColor #90A4AE
  GroupFontSize {r(0.95)}
  GroupHeaderFontSize {r(0.92)}
  DividerBackgroundColor #ECEFF1
  DividerFontSize {r(0.95)}
  MessageAlignment direction
}}
skinparam DatabaseFontSize {S}
skinparam StereotypeFontSize {r(0.92)}
""")
